version: "3.7"

services:
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    env_file: ./.env.local #Here we are using the already existing .env.local file
    ports:
      - "5432:5432"

  redis:
    image: redis
    command: ["redis-server"]
    container_name: redis
    volumes:
      - data:/data
    ports:
      - "6379:6379"

volumes:
  data:
